---
apiVersion: operators.cloud.tencent.com/v1alpha1
kind: Redis
metadata:
  name: example-redis-cluster
spec:
  mode: cluster
  size: 4
  global:
    image: quay.io/opstree/redis:v6.2
    imagePullPolicy: IfNotPresent
    password: "Opstree@1234"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  master:
    service:
      type: ClusterIP
    redisConfig: {}
  slave:
    service:
      type: ClusterIP
    redisConfig: {}
  standalone:
    service:
      type: ClusterIP
  redisConfig: {}
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: cbs
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
